language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
script:
- source ./environment_test.sh
- py.test --cov application tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls --ignore-errors
env:
  global:
  - SECRET_KEY='this is a secret'
  - SETTINGS='config.TestConfig'
  - SECURITY_PASSWORD_SALT= 'a random salt'
  - secure: "nM6uJUmLVjNzdU4ofv37z/qbi98QInJr8F+uraY/3xTE7D2gjUb8i9gGgiek1Gl2bZ6cz82qoCefD6pa4XeooExcFnEST/yb4jPBtauBLSN+FacUn55dMjP9qGewFvZyZ/CgKrpzugjZzlt3B3+/JjF6cmgscCNDcQWowKnZpW0="
deploy:
  provider: heroku
  api_key:
    secure: CM1YAgIGFy9V3srMO9yFuZUn9fZj4jzMxMtr/P3zHG6SOFyiOogAxPtiDgqJjOj8A8w+OonoHcwbyc7VoYgoqMuhtQmhXT4coBRa99sVAN46ug5jZgOaRW1vP2Vt4dqQEkZGynDYwQ2pXzSpJZLSZj4PVxbdszB6aaSE22SnLWQ=
  app: lr-service-frontend
  on:
    repo: LandRegistry/service-frontend
