language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install pytest
script: py.test
env:
- SECRET_KEY='this is a secret' SETTINGS='config.TestConfig' SECURITY_PASSWORD_SALT = 'a random salt'
