export SETTINGS='config.TestConfig'
export DATABASE_URL='sqlite://'
export AUTHENTICATED_SEARCH_API='http://nowhere'
export SECRET_KEY='localdev-not-secret'
export DECISION_URL='http://nowhere'
export MATCHING_URL='http://nowhere'
export OWNERSHIP_URL='http://nowhere'
export OS_API_KEY='no-key-in-test'
