export SETTINGS='config.DevelopmentConfig'
export DATABASE_URL='postgresql://localhost/landregistry_users'
export AUTHENTICATED_SEARCH_API='http://localhost:8003'
export SECRET_KEY='localdev-not-secret'
export DECISION_URL='http://decision.landregistry.local'
