"""empty message

Revision ID: 300ea6564a00
Revises: 4d94a6ed0333
Create Date: 2014-08-28 21:37:43.931951

"""

# revision identifiers, used by Alembic.
revision = '300ea6564a00'
down_revision = '4d94a6ed0333'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from application.auth.models import User

def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_address', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('F', 'M', name='gender_types'), nullable=False))
    op.add_column('users', sa.Column('lrid', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('users', sa.Column('name', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('previous_address', sa.TEXT(), nullable=False))
    op.drop_column('users', 'authenticated')
    op.drop_constraint(u'users_email_key', 'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_email_key', 'users', ['email'], unique=True)
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'previous_address')
    op.drop_column('users', 'name')
    op.drop_column('users', 'lrid')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'current_address')
    ### end Alembic commands ###
