"""empty message

Revision ID: 416dcaf9d750
Revises: None
Create Date: 2014-08-30 10:53:31.482510

"""

# revision identifiers, used by Alembic.
revision = '416dcaf9d750'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('F', 'M', name='gender_types'), nullable=False),
    sa.Column('current_address', sa.TEXT(), nullable=False),
    sa.Column('previous_address', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
