"""empty message

Revision ID: 564960ba0967
Revises: 416dcaf9d750
Create Date: 2014-09-02 20:51:30.218855

"""

# revision identifiers, used by Alembic.
revision = '564960ba0967'
down_revision = '416dcaf9d750'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###
